CREATE TABLE FLTRESV (
  FLIGHT_NUM NUMBER,
  DEPART_TIME TIMESTAMP,
  DURATION NUMBER,
  CAPACITY NUMBER,
  SEASONAL NUMBER(1),
  ORIGIN VARCHAR2(50 BYTE),
  DESTINATION VARCHAR2(50 BYTE),
  REQUEST XMLTYPE
);